<?php
/**
 * FileName: AllowCrossDomain.php
 * ==============================================
 * Copy right 2016-2018
 * ----------------------------------------------
 * This is not a free software, without any authorization is not allowed to use and spread.
 * ==============================================
 * @author: kong | <iwhero@yeah.com>
 * @date  : 2020/6/3 3:42 下午
 */
declare (strict_types = 1);

namespace app\common\middleware;

use Closure;
use think\middleware\AllowCrossDomain as BaesAllowCrossDomain;

class AllowCrossDomain extends BaesAllowCrossDomain
{
    public function handle($request, Closure $next, ?array $header = [])
    {
        $this->header['Access-Control-Allow-Headers'] .= ', X-Token';

        return parent::handle($request, $next, $header); // TODO: Change the autogenerated stub
    }
}